// <auto-generated />
using System;
using FruitRacers.Backend.DataAccess.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FruitRacers.Backend.DataAccess.Migrations
{
    [DbContext(typeof(FruitracersContext))]
    [Migration("20191228144003_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("UserId");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Administrator", b =>
                {
                    b.Property<int>("UserId");

                    b.HasKey("UserId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ImageId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("ParentCategoryId");

                    b.HasKey("CategoryId");

                    b.HasIndex("ImageId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.CustomerBusiness", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsValid");

                    b.Property<string>("LegalForm")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Pec")
                        .HasMaxLength(60);

                    b.Property<string>("Sdi")
                        .HasMaxLength(7);

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("UserId");

                    b.HasIndex("VatNumber")
                        .IsUnique();

                    b.ToTable("CustomerBusinesses");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.DeliveryCompany", b =>
                {
                    b.Property<int>("UserId");

                    b.HasKey("UserId");

                    b.ToTable("DeliveryCompanies");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<int>("OrderState");

                    b.Property<int?>("TimeSlotId");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("SupplierId");

                    b.Property<decimal?>("UnitMultiplier")
                        .HasColumnType("decimal(8, 4)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(5);

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "SupplierId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.OrderSection", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("SupplierId");

                    b.Property<int>("State");

                    b.HasKey("OrderId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrderSections");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Person", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Cf")
                        .IsRequired()
                        .HasColumnName("CF")
                        .HasMaxLength(16);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Price", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProductId");

                    b.Property<int>("Minimum");

                    b.Property<decimal>("UnitMultiplier")
                        .HasColumnType("decimal(8, 4)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<decimal>("Value")
                        .HasColumnType("money");

                    b.HasKey("Type", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool?>("IsEnabled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsLegal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SupplierId");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId");

                    b.Property<int>("CategoryId");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductId");

                    b.Property<int>("ImageId");

                    b.Property<int>("Order");

                    b.HasKey("ProductId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsValid");

                    b.Property<string>("LegalForm")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Pec")
                        .HasMaxLength(60);

                    b.Property<string>("Sdi")
                        .HasMaxLength(7);

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("UserId");

                    b.HasIndex("VatNumber")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.SupplierImage", b =>
                {
                    b.Property<int>("SupplierId");

                    b.Property<int>("ImageId");

                    b.Property<int>("Order");

                    b.HasKey("SupplierId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("SupplierImages");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("SlotCapacity");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("Weekday");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.TimeSlotOverride", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TimeSlotId");

                    b.Property<int>("Offset");

                    b.HasKey("Date", "TimeSlotId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("TimeSlotOverrides");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CookieConsent");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool?>("IsEnabled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("MarketingConsent");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Telephone")
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Address", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Administrator", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("FruitRacers.Backend.Core.Entities.Administrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Category", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Image", "Image")
                        .WithMany("Categories")
                        .HasForeignKey("ImageId");

                    b.HasOne("FruitRacers.Backend.Core.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.CustomerBusiness", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithOne("CustomerBusiness")
                        .HasForeignKey("FruitRacers.Backend.Core.Entities.CustomerBusiness", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.DeliveryCompany", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithOne("DeliveryCompany")
                        .HasForeignKey("FruitRacers.Backend.Core.Entities.DeliveryCompany", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Order", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.HasOne("FruitRacers.Backend.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Orders")
                        .HasForeignKey("TimeSlotId");

                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FruitRacers.Backend.Core.Entities.OrderSection", "OrderSection")
                        .WithMany("Details")
                        .HasForeignKey("OrderId", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.OrderSection", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Order", "Order")
                        .WithMany("Sections")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FruitRacers.Backend.Core.Entities.Supplier", "Supplier")
                        .WithMany("ReceivedOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Person", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("FruitRacers.Backend.Core.Entities.Person", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Price", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Product", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.ProductCategory", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FruitRacers.Backend.Core.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Image", "Image")
                        .WithMany("ProductImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FruitRacers.Backend.Core.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.Supplier", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.User", "User")
                        .WithOne("Supplier")
                        .HasForeignKey("FruitRacers.Backend.Core.Entities.Supplier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.SupplierImage", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.Image", "Image")
                        .WithMany("SupplierImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FruitRacers.Backend.Core.Entities.Supplier", "Supplier")
                        .WithMany("SupplierImages")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FruitRacers.Backend.Core.Entities.TimeSlotOverride", b =>
                {
                    b.HasOne("FruitRacers.Backend.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("TimeSlotOverrides")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
