version: '3.4'

services:
  fruitracers.backend.apilayer:
    image: ${DOCKER_REGISTRY-}fruitracersbackendapilayer
    build:
      context: .
      dockerfile: FruitRacers.Backend.ApiLayer/Dockerfile
